---
kind: pipeline
type: docker
name: CD

steps:
- name: generate emacs
  image: silex/emacs:master-alpine
  commands:
    - apk update && apk add git
    - emacs -Q --script export.el
    - pwd && ls -ahl
    - find / -name '*.org'
    - find / -name '*.md'

- name: generate node
  image: node:19-alpine
  commands:
    - yarn --frozen-lockfile
    - yarn docs:build
    - pwd && ls -ahl

- name: deploy
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    target:
      from_secret: ssh_target
    source: docs/.vuepress/dist/*
    strip_components: 3
    username:
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port:
      from_secret: ssh_port
  when:
    branch:
    - main
    event:
      exclude:
      - pull_request

- name: purge cache
  image: jetrails/drone-cloudflare-caching
  settings:
    api_token:
      from_secret: cloudflare_cache_api
    zone_identifier:
      from_secret: phundrak_com_zone_id
    action: purge_files
    list:
    - https://config.phundrak.com
  when:
    branch:
    - devel
    event:
      exclude:
      - pull_request
