edition = "2018"

enum_discrim_align_threshold = 20

fn_single_line = true

format_code_in_doc_comments = true

format_strings = true

hard_tabs = true

max_width = 80

merge_imports = true

newline_style = Unix

normalize_comments = true

normalize_doc_attributes = true

reorder_impl_items = true

report_fixme = "Always"

todo = "Always"

struct_field_align_threshold = 20

tab_spaces = 2

wrap_comments = true
