#!/usr/bin/fish

while read file
    set -g FILES "$file" $FILES
end

switch "$argv[1]"
    case "d"
        trash $FILES
    case "D"
        rm $FILES
    case "g"
        gimp $FILES
    case "j"
        for f in $FILES
            set basename (echo $f | sed 's/\.[^.]*$//')
            convert $f $basename".jpg"
        end
    case "r"
        echo ROTATE
        echo $FILES
        for f in $FILES
            convert -rotate 90 "$f" "$f"
        end
    case "R"
        for f in $FILES
            convert -rotate 270 "$f" "$f"
        end
    case "y"
        set FILE $FILES[1]
        set TYPE (file -i $FILE | sed -r 's|.*(image/[a-z]+);.*|\1|')
        xclip -sel clip -t "$TYPE" -i "$FILE"
end
