#+title: About this website
#+setupfile: headers

* About this website
** Introduction
This is the config website of Lucien “Phundrak” Cartier-Tilet.

This website is made with [[https://orgmode.org/][org-mode]] and [[https://v2.vuepress.vuejs.org/][Vuepress]] and is entirely free
and open-source. You can find its source code on my Gitea instance
[[https://labs.phundrak.com/phundrak/config.phundrak.com][here]].

** Where is the website hosted?
This website is hosted on my private physical server, located in the
town of Bron in France, near Lyon. All of my websites are also hosted
on this server, except for [[https://labs.phundrak.com][=labs.phundrak.com=]] and =mail.phundrak.com=
which are hosted on servers rented to Scaleway and OVH France
respectively. These servers are also located in France.

** Cookies
*** What are cookies?
Cookies are small files a website saves on your computer or mobile
phone when you visit a website. Although not all sites make use of
them, they are nevertheless extremely common in order to allow
websites to function properly or function properly or more
efficiently.

This website uses some functional cookies in order to remember your
preferences, such as your preferred language or its colour theme.
These cookies are not and cannot be used to track you.

However, as this site is protected by Cloudflare, they may also host
some cookies to remember, for example, that your browser is safe or to
record traffic to the site.

*** How can I control cookies on my computer?
If you don't want Cloudflare to record your browsing activity on my
website, a good ad blocker should do the trick. I personally recommend
[[https://ublockorigin.com/][uBlock Origin]], one of the most effective ad blockers I know of if not
the most effective one.

You can also manually delete cookies from your browser, but given the
number of browsers out there, it might be quicker for you to look up
DuckDuckGo, Qwant or Startpage to do this for your current browser (if
you're worried about cookie usage, I guess you'll want to avoid
Google).

*** What about other methods of tracking users?
There are other more subtle methods of tracking someone on the
internet, or even via emails or any web content rendered on the
screen, such as web beacons (minuscule images). It is also possible to
store Flash cookies or local shared objects.

This site does not use them at all.

** Is there targeted advertisement on this website?
There’s no advertisement to begin with. If you see any, check your
computer and browser for virus, that is not normal.

** How often is this page updated?
It is updated from time to time to reflect any changes in how my
website behaves, or if I notice errors on this page (such as typos). I
might add some user tracking, however don’t worry, Matomo (the service
I would use) would only track you on this website and this website
only. Matomo respects the privacy of a website’s users.

You can see the last update of this page by looking at the last
modification of the file =about.org= on [[https://labs.phundrak.com/phundrak/config.phundrak.com/src/branch/main/docs][this page]].

** I have other questions

And I have the answers! I’ll be more than happy to chat with you by
email, feel free to send me one at [[mailto:lucien@phundrak.com][lucien@phundrak.com]].
